[package]
name = "rust_algo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-crypto = "^0.2"
sha2 = "0.10.2"
sha3 = "0.9.1"
hex = "0.4.3"
structopt = "0.3"

[dev-dependencies]
proptest = "1"
